<?php

use Illuminate\Database\Seeder;

class MunicipioTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        //
        try {
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 1]);
            DB::table("municipio")->insert([ "municipio" => "ANACO", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "ARAGUA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "BRUZUAL", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "CAJIGAL", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "FREITES", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "INDEPENDENCIA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTAD", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "MONAGAS", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "PEÑALVER", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "SIMON RODRIGUEZ", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "SOTILLO", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "GUANIPA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "GUANTA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "PIRITU", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "M.L/DIEGO BAUTISTA U", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "CARVAJAL", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "SANTA ANA", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "MC GREGOR", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "S JUAN CAPISTRANO", "estado_id" => 2]);
            DB::table("municipio")->insert([ "municipio" => "ACHAGUAS", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "MUÑOZ", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "PAEZ", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "PEDRO CAMEJO", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "ROMULO GALLEGOS", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "SAN FERNANDO", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "BIRUACA", "estado_id" => 3]);
            DB::table("municipio")->insert([ "municipio" => "GIRARDOT", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "SANTIAGO MARIÑO", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "JOSE FELIX RIVAS", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "SAN CASIMIRO", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "SAN SEBASTIAN", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "URDANETA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "ZAMORA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "JOSE ANGEL LAMAS", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "SANTOS MICHELENA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "MARIO B IRAGORRY", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "TOVAR", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "CAMATAGUA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "JOSE R REVENGA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "FRANCISCO LINARES A.", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "M.OCUMARE D LA COSTA", "estado_id" => 4]);
            DB::table("municipio")->insert([ "municipio" => "ARISMENDI", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "BARINAS", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "EZEQUIEL ZAMORA", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "OBISPOS", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "PEDRAZA", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "ROJAS", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "SOSA", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "ALBERTO ARVELO T", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "A JOSE DE SUCRE", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "CRUZ PAREDES", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES E. BLANCO", "estado_id" => 5]);
            DB::table("municipio")->insert([ "municipio" => "CARONI", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "CEDEÑO", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "HERES", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "PIAR", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "ROSCIO", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "SIFONTES", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "RAUL LEONI", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "GRAN SABANA", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "EL CALLAO", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "PADRE PEDRO CHIEN", "estado_id" => 6]);
            DB::table("municipio")->insert([ "municipio" => "BEJUMA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "CARLOS ARVELO", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "DIEGO IBARRA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "GUACARA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "MONTALBAN", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "JUAN JOSE MORA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "PUERTO CABELLO", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "SAN JOAQUIN", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "VALENCIA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "LOS GUAYOS", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "NAGUANAGUA", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "SAN DIEGO", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 7]);
            DB::table("municipio")->insert([ "municipio" => "ANZOATEGUI", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "FALCON", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "GIRARDOT", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "MP PAO SN J BAUTISTA", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "RICAURTE", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "SAN CARLOS", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "TINACO", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "LIMA BLANCO", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "ROMULO GALLEGOS", "estado_id" => 8]);
            DB::table("municipio")->insert([ "municipio" => "ACOSTA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "BUCHIVACOA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "CARIRUBANA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "COLINA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "DEMOCRACIA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "FALCON", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "FEDERACION", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "MAUROA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "PETIT", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "SILVA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "ZAMORA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "DABAJURO", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "MONS. ITURRIZA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "LOS TAQUES", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "PIRITU", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "UNION", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "SAN FRANCISCO", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "JACURA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "CACIQUE MANAURE", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "PALMA SOLA", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "URUMACO", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "TOCOPERO", "estado_id" => 9]);
            DB::table("municipio")->insert([ "municipio" => "INFANTE", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "MELLADO", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "MONAGAS", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "RIBAS", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "ROSCIO", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "ZARAZA", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "CAMAGUAN", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "S JOSE DE GUARIBE", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "LAS MERCEDES", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "EL SOCORRO", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "ORTIZ", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "S MARIA DE IPIRE", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "CHAGUARAMAS", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "SAN GERONIMO DE G", "estado_id" => 10]);
            DB::table("municipio")->insert([ "municipio" => "CRESPO", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "IRIBARREN", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "JIMENEZ", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "MORAN", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "PALAVECINO", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "TORRES", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "URDANETA", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES E BLANCO", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "SIMON PLANAS", "estado_id" => 11]);
            DB::table("municipio")->insert([ "municipio" => "ALBERTO ADRIANI", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES BELLO", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ARZOBISPO CHACON", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "CAMPO ELIAS", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "GUARAQUE", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "JULIO CESAR SALAS", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "JUSTO BRICEÑO", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "SANTOS MARQUINA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ANTONIO PINTO S.", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "OB. RAMOS DE LORA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "CARACCIOLO PARRA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "CARDENAL QUINTERO", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "PUEBLO LLANO", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "RANGEL", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "RIVAS DAVILA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "TOVAR", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "TULIO F CORDERO", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "PADRE NOGUERA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ARICAGUA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ZEA", "estado_id" => 12]);
            DB::table("municipio")->insert([ "municipio" => "ACEVEDO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "BRION", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "GUAICAIPURO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "INDEPENDENCIA", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "LANDER", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "PAEZ", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "PAZ CASTILLO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "PLAZA", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "URDANETA", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "ZAMORA", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "CRISTOBAL ROJAS", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "LOS SALIAS", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES BELLO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "SIMON BOLIVAR", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "BARUTA", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "CARRIZAL", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "CHACAO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "EL HATILLO", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "BUROZ", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "PEDRO GUAL", "estado_id" => 13]);
            DB::table("municipio")->insert([ "municipio" => "ACOSTA", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "CARIPE", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "CEDEÑO", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "EZEQUIEL ZAMORA", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "MATURIN", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "PIAR", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "PUNCERES", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "SOTILLO", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "AGUASAY", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "SANTA BARBARA", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "URACOA", "estado_id" => 14]);
            DB::table("municipio")->insert([ "municipio" => "ARISMENDI", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "DIAZ", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "GOMEZ", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "MANEIRO", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "MARCANO", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "MARIÑO", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "PENIN. DE MACANAO", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "VILLALBA(I.COCHE)", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "TUBORES", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "ANTOLIN DEL CAMPO", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "GARCIA", "estado_id" => 15]);
            DB::table("municipio")->insert([ "municipio" => "ARAURE", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "ESTELLER", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "GUANARE", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "GUANARITO", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "OSPINO", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "PAEZ", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "TUREN", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "M.JOSE V DE UNDA", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "AGUA BLANCA", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "PAPELON", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "GENARO BOCONOITO", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "S RAFAEL DE ONOTO", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "SANTA ROSALIA", "estado_id" => 16]);
            DB::table("municipio")->insert([ "municipio" => "ARISMENDI", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "BENITEZ", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "BERMUDEZ", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "CAJIGAL", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "MARIÑO", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "MEJIA", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "MONTES", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "RIBERO", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "VALDEZ", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES E BLANCO", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES MATA", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "CRUZ S ACOSTA", "estado_id" => 17]);
            DB::table("municipio")->insert([ "municipio" => "AYACUCHO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "INDEPENDENCIA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "CARDENAS", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "JAUREGUI", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "JUNIN", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "LOBATERA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SAN CRISTOBAL", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "URIBANTE", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "CORDOBA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "GARCIA DE HEVIA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "GUASIMOS", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "MICHELENA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTADOR", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "PANAMERICANO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "PEDRO MARIA UREÑA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES BELLO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "FERNANDEZ FEO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "LIBERTAD", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SAMUEL MALDONADO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SEBORUCO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "ANTONIO ROMULO C", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "FCO DE MIRANDA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "JOSE MARIA VARGA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "RAFAEL URDANETA", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SIMON RODRIGUEZ", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "TORBES", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "SAN JUDAS TADEO", "estado_id" => 18]);
            DB::table("municipio")->insert([ "municipio" => "RAFAEL RANGEL", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "BOCONO", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "CARACHE", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "ESCUQUE", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "TRUJILLO", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "URDANETA", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "VALERA", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "CANDELARIA", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "MONTE CARMELO", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "MOTATAN", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "PAMPAN", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "S RAFAEL CARVAJAL", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "ANDRES BELLO", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "JOSE F M CAÑIZAL", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "JUAN V CAMPO ELI", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "LA CEIBA", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "PAMPANITO", "estado_id" => 19]);
            DB::table("municipio")->insert([ "municipio" => "BOLIVAR", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "BRUZUAL", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "NIRGUA", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "SAN FELIPE", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "URACHICHE", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "PEÑA", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "JOSE ANTONIO PAEZ", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "LA TRINIDAD", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "COCOROTE", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "INDEPENDENCIA", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "ARISTIDES BASTID", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "MANUEL MONGE", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "VEROES", "estado_id" => 20]);
            DB::table("municipio")->insert([ "municipio" => "BARALT", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "SANTA RITA", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "COLON", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "MARA", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "MARACAIBO", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "MIRANDA", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "PAEZ", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "MACHIQUES DE P", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "SUCRE", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "LA CAÑADA DE U.", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "LAGUNILLAS", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "CATATUMBO", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "M/ROSARIO DE PERIJA", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "CABIMAS", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "VALMORE RODRIGUEZ", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "JESUS E LOSSADA", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "ALMIRANTE P", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "SAN FRANCISCO", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "JESUS M SEMPRUN", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "FRANCISCO J PULG", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "SIMON BOLIVAR", "estado_id" => 21]);
            DB::table("municipio")->insert([ "municipio" => "ATURES", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "ATABAPO", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "MAROA", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "RIO NEGRO", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "AUTANA", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "MANAPIARE", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "ALTO ORINOCO", "estado_id" => 22]);
            DB::table("municipio")->insert([ "municipio" => "TUCUPITA", "estado_id" => 23]);
            DB::table("municipio")->insert([ "municipio" => "PEDERNALES", "estado_id" => 23]);
            DB::table("municipio")->insert([ "municipio" => "ANTONIO DIAZ", "estado_id" => 23]);
            DB::table("municipio")->insert([ "municipio" => "CASACOIMA", "estado_id" => 23]);
            DB::table("municipio")->insert([ "municipio" => "VARGAS", "estado_id" => 24]);
        } catch (Exception $ex) {
            if ($ex->getCode() == 23505) {
                echo "Registros ya existentes ";
            } else {
                echo "Error: {$ex->getMessage()} ";
            }
        }
    }

}
